SELECT _FIVETRAN_ID,
        PAYMENT_METHOD,
        TAX_RATE,
        PHONE,
        ORDER_AT AS ORDER_TS,
        ORDER_ID,
        SHIPPING_ADDRESS,
        PAYMENT_INFO,
        STATE,
        SESSION_ID,
        CAST(REPLACE(SHIPPING_COST,'USD ','') AS FLOAT) AS SHIPPING_COST,
        CLIENT_NAME,
        _FIVETRAN_DELETED,
        _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
FROM {{source('snowflake','orders')}}